"""manual decisions by trade reference, file hashes

Revision ID: 5634bffe18c6
Revises: a47394fea457
Create Date: 2026-09-04 18:50:56.170525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5634bffe18c6'
down_revision: Union[str, Sequence[str], None] = 'a47394fea457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('our_external_id', sa.String(), nullable=True),
    sa.Column('other_external_id', sa.String(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('manual_matches')
    op.add_column('reconciliation_runs', sa.Column('our_file_hash', sa.String(), nullable=True))
    op.add_column('reconciliation_runs', sa.Column('other_file_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_runs', 'other_file_hash')
    op.drop_column('reconciliation_runs', 'our_file_hash')
    op.create_table('manual_matches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('our_transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('other_transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resolved_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['other_transaction_id'], ['transactions.id'], name=op.f('manual_matches_other_transaction_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['our_transaction_id'], ['transactions.id'], name=op.f('manual_matches_our_transaction_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('manual_matches_pkey'))
    )
    op.drop_table('manual_decisions')
    # ### end Alembic commands ###
